# Generated by Django 3.2.16 on 2023-02-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssettings',
            name='using_hand',
            field=models.CharField(default='right', max_length=10),
        ),
    ]
