# Generated by Django 4.2.30 on 2026-07-12 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userssettings_using_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssettings',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userssettings',
            name='reminder_time',
            field=models.CharField(blank=True, default='21:00', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
