# Generated by Django 3.2 on 2022-12-26 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0002_savingrelated_create_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedWalletList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='savingrelated',
            name='saving_where',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='savingrelated',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='savings',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(default='', max_length=30)),
                ('wallet_number', models.CharField(blank=True, max_length=24, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('wallet_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.predefinedwalletlist')),
                ('wallet_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
