# Generated by Django 3.2 on 2022-12-28 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20221227_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.predefinedwalletlist'),
        ),
    ]
