# Generated by Django 3.2 on 2022-12-29 05:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0005_alter_wallet_wallet_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('wallet_info', 'wallet_of')},
        ),
    ]
