# Generated by Django 3.2.16 on 2022-12-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_alter_wallet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedwalletlist',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
