# Generated by Django 3.2.16 on 2022-12-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_alter_predefinedwalletlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savings',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='savings.wallet'),
            preserve_default=False,
        ),
    ]
