# Generated by Django 3.2.16 on 2022-12-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_savings_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='saving_related_id',
        ),
    ]
