# Generated by Django 3.2.16 on 2023-01-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0010_savings_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingrelated',
            name='saving_where',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savingrelated',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
