# Generated by Django 3.2 on 2023-09-05 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0011_auto_20230104_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_from_wallet', models.CharField(default='', max_length=20)),
                ('transfer_to_wallet', models.CharField(default='', max_length=20)),
                ('prev_amount_of_transfered_from', models.IntegerField()),
                ('current_amount_of_transfered_from', models.IntegerField()),
                ('prev_amount_of_transfered_to', models.IntegerField()),
                ('current_amount_of_transfered_to', models.IntegerField()),
                ('transfered_amount', models.IntegerField()),
                ('tansfered_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
