# Generated by Django 3.2 on 2023-09-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0013_monthlybalancesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalancesummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
