# Generated by Django 4.2.30 on 2026-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0014_monthlybalancesummary_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdetails',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferdetails',
            name='transfer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
