# Generated by Django 4.2.30 on 2026-07-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savings', '0015_transferdetails_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('entry_type', models.CharField(choices=[('take', 'Take Loan'), ('give', 'Give Loan'), ('repay', 'Repay Loan'), ('collect', 'Collect Return')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.wallet')),
            ],
        ),
    ]
