# Generated by Django 3.2 on 2022-10-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_info', models.CharField(default='', max_length=50)),
                ('short_description', models.CharField(default='', max_length=255)),
                ('cost_field', models.CharField(default='', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(default='', max_length=255)),
                ('cost_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('cost_related_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costs.costrelated')),
            ],
        ),
    ]
