# Generated by Django 3.2 on 2022-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_costrelated_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
