# Generated by Django 3.2 on 2022-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_alter_costs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrelated',
            name='cost_field',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='costrelated',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
