# Generated by Django 3.2 on 2022-12-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_alter_wallet_unique_together'),
        ('costs', '0004_auto_20221227_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='savings.wallet'),
            preserve_default=False,
        ),
    ]
