# Generated by Django 3.2.16 on 2023-01-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_costs_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrelated',
            name='cost_field',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='costrelated',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
