# Generated by Django 3.2 on 2022-11-05 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_incomerelated_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomes',
            old_name='saving_date',
            new_name='income_date',
        ),
    ]
