# Generated by Django 3.2 on 2022-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_rename_saving_date_incomes_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerelated',
            name='income_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='incomerelated',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='incomes',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
